services:
  - type: web
    name: byd-queue-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: STAFF_PIN
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: CORS_ORIGIN
        value: https://queuingsystembyd-web.vercel.app
      - key: TZ
        value: Asia/Manila
